# -*- coding: utf-8 -*-
# flake8: noqa
"""Traducciones al español para GPS Road Builder."""
from ._locale import build_catalog

translations = build_catalog({
 'window_title':'GPS Road Builder (RidgeSlide)','plugin_description':'Reconstruye una red de caminos y senderos desde trazas GPS con RidgeSlide.','info':'Información','error':'Error','warning':'Advertencia','close':'Cerrar','cancel':'Cancelar','ok':'Aceptar','details':'Detalles','coming_soon':'Próximamente','phase0_notice':'Este paso se implementará en las siguientes fases.',
 'header_support':'Apoyar','header_about_author':'Acerca de','support_tip':'Apoye el desarrollo de este complemento.','author_tip':'Información sobre el autor', 'tab_data':'Datos','tab_preprocess':'Preproceso','tab_density':'Densidad / RidgeSlide','tab_graph':'Grafo','tab_scale':'Escala','tab_postprocess':'Posproceso','tab_output':'Salida','tab_deps':'Dependencias', 'build_graph':'Construir grafo de caminos','test_run':'Prueba (área)','building':'Construyendo…','clear_logs':'Limpiar registro','progress':'Progreso','logs':'Registro','results':'Resultados','col_stage':'Etapa','col_status':'Estado','col_message':'Mensaje','status_ok':'Correcto',
 'metric_input':'Puntos de entrada','metric_duplicates_removed':'Duplicados eliminados','metric_near_dup_removed':'Casi duplicados eliminados','metric_reb_removed':'Interferencias/suplantación eliminadas','metric_tracks':'Trazas','metric_tiles':'Teselas','metric_edges':'Aristas','metric_nodes':'Nodos','duration_hours':'{0} h','duration_minutes':'{0} min','duration_seconds':'{0} s','log_ready':'GPS Road Builder está listo. Elija datos y parámetros y construya el grafo de caminos.',
 'deps_intro':'GPS Road Builder usa las bibliotecas incluidas en QGIS; las siguientes son aceleradores opcionales y solo se instalan por acción expresa.','deps_col_package':'Biblioteca','deps_col_purpose':'Finalidad','deps_col_status':'Estado','deps_status_installed':'instalada','deps_status_missing':'no instalada','deps_install_method':'Método de instalación:','deps_method_auto':'Automático','deps_method_pip':'pip → carpeta del complemento','deps_method_wheels':'Wheels precompilados (espejo)','deps_method_folder':'Desde carpeta local','deps_install_selected':'Instalar seleccionadas','deps_recheck':'Comprobar de nuevo','deps_installing':'Instalando {0}…','deps_install_done':'Instalado: {0}','deps_install_failed':'Error de instalación: {0}','deps_pip_unavailable':'pip no está disponible en Python de QGIS; use «Wheels precompilados» o «Desde carpeta local».','deps_choose_folder':'Elija la carpeta con wheels (*.whl)','deps_purpose_numba':'Núcleo RidgeSlide rápido (JIT, paralelo)','deps_purpose_pandas':'Datos tabulares y soporte CSV/XLSX','deps_purpose_skimage':'Esqueletización de la máscara de densidad','deps_purpose_pyarrow':'Lectura CSV más rápida','deps_purpose_sklearn':'Preagrupación DBSCAN opcional','deps_optional':'opcional','installing':'Instalando dependencias…','downloading':'Descargando…','extracting':'Extrayendo…',
 'preset_label':'Preajuste:','preset_apply':'Aplicar','preset_save':'Guardar','preset_load':'Cargar','preset_applied':'Preajuste aplicado','preset_saved':'Preajuste guardado','preset_loaded':'Preajuste cargado','cache_group':'Resultados intermedios (puntos de control)','cache_dir':'Carpeta de caché','cache_start':'Comenzar en etapa','cache_stop':'Detener tras etapa','stage_none':'—','stage_points':'Puntos limpios','stage_tracks':'Trazas proyectadas','stopped_after':'Detenido tras etapa','preset_mixed':'Mixto (predeterminado)','preset_highway':'Caminos de saca','preset_spurs':'Ramales / vías de arrastre','preset_dense_tracks':'Trazas densas (correr / ciclismo)','preset_urban_logistics':'Vehículos urbanos / logística','preset_osm_traces':'Trazas OSM (heterogéneas)','preset_sparse_slide':'Disperso / RidgeSlide (recomendado)','preset_sparse_slide_accurate':'Disperso / RidgeSlide (preciso)','preset_sparse_ais':'Buques dispersos / AIS','preset_fgis_kde':'Disperso / KDE (experimental)',
 'data_group':'Datos de entrada','data_source':'Fuente de entrada','src_files':'Archivos CSV/XLSX (carpeta)','src_layer':'Capa del proyecto (puntos/líneas)','src_vfile':'Archivo GPX / KML / SHP','data_folder':'Carpeta CSV/XLSX (recursiva)','data_browse':'Examinar carpeta','data_scan':'Escanear','data_season_split':'Separar por temporadas','data_files_found':'Archivos encontrados: {0}','default_layer_name':'Red vial GPS', 'pp_group':'Preprocesamiento','pp_mindist':'Reducir puntos cercanos, m','pp_vmax':'Velocidad máxima, km/h','pp_amax':'Aceleración máxima, m/s²','pp_gap_dt':'Salto temporal, min','pp_gap_ds':'Salto de distancia, m','pp_resample':'Paso de remuestreo K, m','pp_reb':'Filtro REB / antisuplantación',
 'method_group':'Método y motores','method_label':'Método','method_slide':'Densidad + RidgeSlide (trazas densas)','method_kde':'KDE + búfer (trazas dispersas)','ds_slide_backend':'Motor RidgeSlide','ds_skel_backend':'Esqueletizador','backend_auto':'Automático','backend_numba':'numba (rápido)','backend_numpy':'numpy (lento, referencia)','skel_skimage':'scikit-image','skel_medial':'Eje medial (línea central)','skel_zhang':'Zhang–Suen (integrado)','kde_radius':'Radio KDE, m','kde_buffer':'Búfer de huecos, m','ds_group':'Densidad y RidgeSlide','ds_cell':'Tamaño de celda τ, m','ds_sigma1':'Suavizado σ1, px','ds_sigma2':'Suavizado σ2, px','ds_sharpness':'Nitidez del núcleo','ds_advanced':'Avanzado','ds_min_loops':'Bucles mínimos de RidgeSlide','ds_max_loops':'Bucles máximos de RidgeSlide',
 'gr_group':'Grafo','gr_eps_mode':'Umbral ε','gr_eps_auto':'Automático (Otsu)','gr_eps_manual':'Manual','gr_eps_adaptive':'Adaptativo','gr_eps_percentile':'Percentil (disperso)','gr_eps_value':'Valor ε','gr_eps_pct_value':'Percentil de umbral, %','gr_dp':'Douglas–Peucker, m','gr_fmin':'Frecuencia mínima de arista f','gr_lmin':'Longitud mínima de arista l, m','gr_spur':'Eliminar ramales colgantes más cortos que, m','gr_fill_holes':'Rellenar huecos de máscara, m','gr_loop_min':'Eliminar microbucles más cortos que, m','gr_smooth':'Suavizado (Chaikin), iteraciones','gr_protect':'Proteger caminos largos poco frecuentes', 'sc_group':'Escala (dividir y unir)','sc_mode':'Teselado','sc_auto':'Automático','sc_off':'Desactivado','sc_forced':'Forzado','sc_nx':'Teselas X','sc_ny':'Teselas Y','sc_maxpoints':'Máx. puntos por tesela',
 'out_group':'Salida','out_crs':'CRS de salida','out_layer_name':'Nombre de capa','out_add_layer':'Añadir capa de resultado al proyecto','out_style_freq':'Ancho según frecuencia','out_export_group':'Exportar','out_export_format':'Formato','out_export_path':'Archivo','out_export_browse':'Examinar','out_export_none':'Ninguno','out_export_geojson':'GeoJSON','out_export_graphml':'GraphML','out_export_gpkg':'GeoPackage','out_export_shp':'Shapefile','export_done':'Exportado a','export_failed':'Error de exportación',
 'pt_conn_group':'Conectividad del grafo','pt_connect_gap':'Unir huecos dentro del radio, m','pt_bridge_facing':'Unir extremos enfrentados hasta, m','pt_stitch':'Unir componentes en una red hasta, m','pt_break':'Cortar aristas en cruces (crear uniones)','pt_junction':'Consolidar grupos de uniones dentro de, m','pt_min_component':'Eliminar componentes más cortos que, m','pt_keep_largest':'Conservar solo la red mayor','pt_apply_group':'Aplicar a un grafo existente','pt_source':'Fuente del grafo','pt_source_last':'Último resultado','pt_source_layer':'Capa del proyecto','pt_apply':'Aplicar posproceso','pt_done':'Posproceso aplicado','pt_no_graph':'No hay grafo: construya uno o seleccione una capa de líneas.','aoi_group':'Área de interés (AOI)','aoi_source_label':'Fuente de AOI','aoi_none':'Sin recorte','aoi_file':'Polígono desde archivo','aoi_layer':'Capa del proyecto','aoi_browse':'Elegir archivo','aoi_load_failed':'No se pudo cargar el polígono AOI','eta':'Tiempo restante','steps_plan':'Pasos','libs_active':'Bibliotecas disponibles','tab_overview':'Resumen','hist_frequency_title':'Frecuencia de aristas','hist_length_title':'Longitud de aristas','build_started':'Construcción iniciada','build_no_folder':'Primero elija una carpeta o archivos de datos.','build_no_input':'No se pudieron obtener puntos de la capa/archivo. Compruebe la fuente de entrada.','build_done':'Grafo de caminos construido','build_failed':'Error de construcción','build_cancelled':'Construcción cancelada','result_edges':'aristas','result_nodes':'nodos','result_length_km':'longitud total','layer_added':'Capa de resultado añadida al proyecto',
 'version':'Versión','author':'Autor','contact':'Contacto','year':'Año','organization':'Organización','multilingual_support':'Interfaz multilingüe (12 idiomas).','about_subtitle':'Reconstruir redes de caminos y senderos desde trazas GPS','about_algorithm_title':'RidgeSlide — el motor','about_algorithm_text':'Este complemento es una interfaz de QGIS para RidgeSlide, que consolida trazas GPS ruidosas en líneas centrales de caminos.','donation_title':'Apoyar el desarrollo','donation_window_title':'☕ Apoye el desarrollo','donation_description':'GPS Road Builder se desarrolla y mantiene en tiempo libre. Si le resulta útil, puede apoyar su desarrollo. ¡Gracias!','donation_kofi':'☕ Ko-fi','donation_tbank':'💳 T-Bank','donation_github':'🐙 GitHub Sponsors',
}, 'configuración', 'Ayuda: ', 'Configuración: ')
