# -*- coding: utf-8 -*-
# flake8: noqa
"""简体中文 translations for GPS Road Builder."""
from ._locale import build_catalog

translations = build_catalog({
    'window_title': 'GPS Road Builder (RidgeSlide)', 'plugin_description': '使用 RidgeSlide 从原始 GPS 轨迹重建道路和路径网络。',
    'info': '信息', 'error': '错误', 'warning': '警告', 'close': '关闭', 'cancel': '取消', 'ok': '确定', 'details': '详细信息', 'coming_soon': '即将推出', 'phase0_notice': '该步骤将在后续开发阶段实现。',
    'header_support': '支持', 'header_about_author': '关于', 'support_tip': '支持此插件的开发。', 'author_tip': '插件作者信息',
    'tab_data': '数据', 'tab_preprocess': '预处理', 'tab_density': '密度 / RidgeSlide', 'tab_graph': '图形', 'tab_scale': '规模', 'tab_postprocess': '后处理', 'tab_output': '输出', 'tab_deps': '依赖项',
    'build_graph': '构建道路图', 'test_run': '测试运行（区域）', 'building': '正在构建…', 'clear_logs': '清除日志',
    'progress': '进度', 'logs': '日志', 'results': '结果', 'col_stage': '阶段', 'col_status': '状态', 'col_message': '消息', 'status_ok': '正常',
    'metric_input': '输入点', 'metric_duplicates_removed': '已删除重复项', 'metric_near_dup_removed': '已删除近重复项', 'metric_reb_removed': '已删除干扰/欺骗', 'metric_tracks': '轨迹', 'metric_tiles': '瓦片', 'metric_edges': '边', 'metric_nodes': '节点', 'duration_hours': '{0} 小时', 'duration_minutes': '{0} 分钟', 'duration_seconds': '{0} 秒', 'log_ready': 'GPS Road Builder 已就绪。请选择数据和参数，然后构建道路图。',
    'deps_intro': 'GPS Road Builder 使用 QGIS 提供的库；以下为可选加速库，只会在您明确操作后安装。', 'deps_col_package': '库', 'deps_col_purpose': '用途', 'deps_col_status': '状态', 'deps_status_installed': '已安装', 'deps_status_missing': '未安装', 'deps_install_method': '安装方式：', 'deps_method_auto': '自动', 'deps_method_pip': 'pip → 插件文件夹', 'deps_method_wheels': '预编译 wheel（镜像）', 'deps_method_folder': '从本地文件夹', 'deps_install_selected': '安装所选项', 'deps_recheck': '重新检查', 'deps_installing': '正在安装 {0}…', 'deps_install_done': '已安装：{0}', 'deps_install_failed': '安装失败：{0}', 'deps_pip_unavailable': 'QGIS Python 中没有 pip；请使用“预编译 wheel”或“从本地文件夹”。', 'deps_choose_folder': '选择包含 wheel (*.whl) 的文件夹', 'deps_purpose_numba': '快速 RidgeSlide 核心（JIT、并行）', 'deps_purpose_pandas': '表格数据及 CSV/XLSX 支持', 'deps_purpose_skimage': '密度掩膜骨架化', 'deps_purpose_pyarrow': '更快读取 CSV', 'deps_purpose_sklearn': '可选 DBSCAN 预聚类', 'deps_optional': '可选',
    'installing': '正在安装依赖项…', 'downloading': '正在下载…', 'extracting': '正在解压…',
    'preset_label': '预设：', 'preset_apply': '应用', 'preset_save': '保存', 'preset_load': '加载', 'preset_applied': '已应用预设', 'preset_saved': '已保存预设', 'preset_loaded': '已加载预设', 'cache_group': '中间结果（检查点）', 'cache_dir': '缓存文件夹', 'cache_start': '起始阶段', 'cache_stop': '结束阶段', 'stage_none': '—', 'stage_points': '清理后的点', 'stage_tracks': '已投影轨迹', 'stopped_after': '在此阶段后停止',
    'preset_mixed': '混合（默认）', 'preset_highway': '运材道路', 'preset_spurs': '支路 / 集材道', 'preset_dense_tracks': '密集轨迹（跑步 / 骑行）', 'preset_urban_logistics': '城市车辆 / 物流', 'preset_osm_traces': 'OSM 轨迹（异构）', 'preset_sparse_slide': '稀疏 / RidgeSlide（推荐）', 'preset_sparse_slide_accurate': '稀疏 / RidgeSlide（精确）', 'preset_sparse_ais': '稀疏船舶 / AIS', 'preset_fgis_kde': '稀疏 / KDE（实验性）',
    'data_group': '输入数据', 'data_source': '输入来源', 'src_files': 'CSV/XLSX 文件（文件夹）', 'src_layer': '项目图层（点/线）', 'src_vfile': 'GPX / KML / SHP 文件', 'data_folder': 'CSV/XLSX 文件夹（递归）', 'data_browse': '浏览文件夹', 'data_scan': '扫描', 'data_season_split': '按季节拆分', 'data_files_found': '找到文件：{0}', 'default_layer_name': 'GPS 道路网络',
    'pp_group': '预处理', 'pp_mindist': '稀疏近点，米', 'pp_vmax': '最大速度，km/h', 'pp_amax': '最大加速度，m/s²', 'pp_gap_dt': '时间间隔，分钟', 'pp_gap_ds': '距离间隔，米', 'pp_resample': '重采样步长 K，米', 'pp_reb': 'REB / 反欺骗过滤器',
    'method_group': '方法与后端', 'method_label': '方法', 'method_slide': '密度 + RidgeSlide（密集轨迹）', 'method_kde': 'KDE + 缓冲区（稀疏轨迹）', 'ds_slide_backend': 'RidgeSlide 后端', 'ds_skel_backend': '骨架化器', 'backend_auto': '自动', 'backend_numba': 'numba（快速）', 'backend_numpy': 'numpy（慢，参考）', 'skel_skimage': 'scikit-image', 'skel_medial': '中轴（中心线）', 'skel_zhang': 'Zhang–Suen（内置）', 'kde_radius': 'KDE 半径，米', 'kde_buffer': '间隙缓冲区，米',
    'ds_group': '密度与 RidgeSlide', 'ds_cell': '单元格大小 τ，米', 'ds_sigma1': '平滑 σ1，像素', 'ds_sigma2': '平滑 σ2，像素', 'ds_sharpness': '核锐度', 'ds_advanced': '高级', 'ds_min_loops': 'RidgeSlide 最小循环', 'ds_max_loops': 'RidgeSlide 最大循环',
    'gr_group': '图形', 'gr_eps_mode': '阈值 ε', 'gr_eps_auto': '自动（Otsu）', 'gr_eps_manual': '手动', 'gr_eps_adaptive': '自适应', 'gr_eps_percentile': '百分位数（稀疏）', 'gr_eps_value': 'ε 值', 'gr_eps_pct_value': '阈值百分位数，%', 'gr_dp': 'Douglas–Peucker，米', 'gr_fmin': '最小边频率 f', 'gr_lmin': '最小边长度 l，米', 'gr_spur': '移除短于此值的悬枝，米', 'gr_fill_holes': '填充掩膜孔洞，米', 'gr_loop_min': '移除短于此值的微环，米', 'gr_smooth': '平滑（Chaikin），次数', 'gr_protect': '保护罕见长道路',
    'sc_group': '规模（拆分与合并）', 'sc_mode': '瓦片化', 'sc_auto': '自动', 'sc_off': '关闭', 'sc_forced': '强制', 'sc_nx': '瓦片 X', 'sc_ny': '瓦片 Y', 'sc_maxpoints': '每瓦片最大点数',
    'out_group': '输出', 'out_crs': '输出 CRS', 'out_layer_name': '图层名称', 'out_add_layer': '将结果图层添加到项目', 'out_style_freq': '按频率设置线宽', 'out_export_group': '导出', 'out_export_format': '格式', 'out_export_path': '文件', 'out_export_browse': '浏览', 'out_export_none': '无', 'out_export_geojson': 'GeoJSON', 'out_export_graphml': 'GraphML', 'out_export_gpkg': 'GeoPackage', 'out_export_shp': 'Shapefile', 'export_done': '已导出到', 'export_failed': '导出失败',
    'ds_slide_close': '掩膜闭合（RidgeSlide），米', 'pt_conn_group': '图连通性', 'pt_connect_gap': '连接半径内的间隙，米', 'pt_bridge_facing': '连接相对死端至，米', 'pt_stitch': '合并组件为一个网络至，米', 'pt_break': '在交叉处断开边（创建路口）', 'pt_junction': '合并路口簇范围，米', 'pt_min_component': '移除短于此值的组件，米', 'pt_keep_largest': '仅保留最大网络', 'pt_apply_group': '应用到现有图', 'pt_source': '图来源', 'pt_source_last': '上次结果', 'pt_source_layer': '项目图层', 'pt_apply': '应用后处理', 'pt_done': '已应用后处理', 'pt_no_graph': '没有图：请先构建图或选择线图层。',
    'aoi_group': '关注区域（AOI）', 'aoi_source_label': 'AOI 来源', 'aoi_none': '不裁剪', 'aoi_file': '文件中的多边形', 'aoi_layer': '项目图层', 'aoi_browse': '选择文件', 'aoi_load_failed': '无法加载 AOI 多边形', 'eta': '预计剩余时间', 'steps_plan': '步骤', 'libs_active': '可用库', 'tab_overview': '概览', 'hist_frequency_title': '边频率', 'hist_length_title': '边长度', 'build_started': '已开始构建', 'build_no_folder': '请先选择数据文件夹或文件。', 'build_no_input': '无法从图层/文件获取点。请检查输入来源。', 'build_done': '道路图已构建', 'build_failed': '构建失败', 'build_cancelled': '已取消构建', 'result_edges': '边', 'result_nodes': '节点', 'result_length_km': '总长度', 'layer_added': '已将结果图层添加到项目',
    'version': '版本', 'author': '作者', 'contact': '联系', 'year': '年份', 'organization': '组织', 'multilingual_support': '多语言界面（12 种语言）。', 'about_subtitle': '从 GPS 轨迹重建道路/路径网络', 'about_algorithm_title': 'RidgeSlide — 引擎', 'about_algorithm_text': '该插件是 RidgeSlide 的 QGIS 前端，用于把有噪声的 GPS 轨迹汇总为清晰的道路中心线。', 'donation_title': '支持开发', 'donation_window_title': '☕ 支持开发', 'donation_description': 'GPS Road Builder 在业余时间开发和维护。若它对您有帮助，欢迎支持后续开发。谢谢！', 'donation_kofi': '☕ Ko-fi', 'donation_tbank': '💳 T-Bank', 'donation_github': '🐙 GitHub Sponsors',
}, '设置', '提示：', '设置：')
